name: Build and release client
on:
  push:
    branches:
      - main
    tags:
      - v*
    paths:
      - client/**
      - .github/workflows/build-client.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.23.4"
      - uses: oven-sh/setup-bun@v2
      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: mingw-w64 libgtk-3-0 libwebkit2gtk-4.0-37 libgtk-3-dev libwebkit2gtk-4.0-dev
          version: 1.0

      - name: Run build script
        run: cd client && REF_NAME=${{ github.ref_name }} ./build.sh

      - name: Create a release with the zip files in client/build
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/*.zip
