name: Build server container image
on:
  push:
    branches:
      - main
    tags:
      - v*
    paths:
      - server/**
      - .github/workflows/build-server.yaml

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.23.4"

      - name: Run build script
        run: cd server && ./build.sh

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: server
          file: server/Containerfile
          push: true
          tags: |
            ghcr.io/s1adem4n/boyl-server:latest
            ghcr.io/s1adem4n/boyl-server:${{ github.ref_name }}
            ghcr.io/s1adem4n/boyl-server:${{ github.sha }}
